name: CI Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      libraries: |
        apt:
          - libxkbcommon-x11-0
          - libgfortran5
        brew:
          - enchant

      envs: |
        # Code style
        - linux: codestyle
          coverage: false

        - macos: py310-test
          PLAT: arm64
          INTERFACE64: ''
          platform: [a64]
